
CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
	ID_FUNCIONARIO int AUTO_INCREMENT PRIMARY KEY NOT NULL, 
    NOME VARCHAR(45) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
    ENDERECO VARCHAR(64) NOT NULL,
    TELEFONE VARCHAR(11) NOT NULL,
    EMAIL VARCHAR(65) NOT NULL,
    GENERO VARCHAR(20),
    DATA_ADMISSAO DATE NOT NULL,
    DATA_SAIDA DATE,
    DEPARTAMENTO VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS FACILITADORES (
	ID_FACILITADOR int AUTO_INCREMENT PRIMARY KEY NOT NULL, 
	ID_FUNCIONARIO int NOT NULL, 
    SKILL VARCHAR(45)
);
ALTER TABLE FACILITADORES ADD CONSTRAINT FOREIGN KEY (ID_FUNCIONARIO)
REFERENCES FUNCIONARIOS(ID_FUNCIONARIO);


