CREATE DATABASE IF NOT EXISTS RESILIA;

USE RESILIA;

CREATE TABLE IF NOT EXISTS TB_CURSOS(
ID_CURSOS VARCHAR (100) NOT NULL,
VALOR_CURSOS DECIMAL (10,2) NOT NULL,
FORMAPAGAMENTO_CURSOS VARCHAR(100) NOT NULL
);

