CREATE DATABASE IF NOT EXISTS RESILIA

USE RESILIA;

CREATE TABLE IF NOT EXISTS TB_ALUNOS (
ID_ALUNO INTEGER PRIMARY KEY AUTO_INCREMENT,
NOME_ALUNO VARCHAR(100) NOT NULL,
CPF_ALUNO BIGINT(11) NOT NULL,
DATA_NASCIMENTO_ALUNO DATE,
ENDERECO VARCHAR(150),
TELEFONE BIGINT(13),
EMAIL VARCHAR(80),
GENERO VARCHAR(1)
)

CREATE TABLE IF NOT EXISTS TB_MATRICULA (
ID_ALUNO INT NOT NULL,
ID_MATRICULA INT NOT NULL AUTO_INCREMENT,
ID_CURSO INT NOT NULL,
TURNO SMALLINT(1),
ID_TURMA INT NOT NULL,
ID_MODULO INT NOT NULL
)